"""Event and Alert dataclasses."""

from dataclasses import dataclass, asdict
from datetime import datetime
from typing import Optional


@dataclass
class SecurityEvent:
    """Represents a normalized security event from any OS."""
    
    id: Optional[int] = None
    timestamp: Optional[datetime] = None
    os_name: Optional[str] = None
    event_type: Optional[str] = None  # FAILED_LOGIN, SUCCESS_LOGIN, SUDO_COMMAND, PRIV_ESCALATION
    username: Optional[str] = None
    source_ip: Optional[str] = None
    process_name: Optional[str] = None
    raw_message: Optional[str] = None
    
    def to_dict(self):
        """Convert to dictionary with ISO format timestamps."""
        data = asdict(self)
        if self.timestamp:
            data['timestamp'] = self.timestamp.isoformat()
        return data


@dataclass
class Alert:
    """Represents a security alert generated by rules."""
    
    id: Optional[int] = None
    timestamp: Optional[datetime] = None
    alert_type: Optional[str] = None  # BRUTE_FORCE_SUSPECTED, SUSPICIOUS_SUDO, etc.
    severity: Optional[str] = None  # INFO, WARNING, CRITICAL
    description: Optional[str] = None
    related_event_ids: Optional[str] = None  # Comma-separated IDs
    
    def to_dict(self):
        """Convert to dictionary with ISO format timestamps."""
        data = asdict(self)
        if self.timestamp:
            data['timestamp'] = self.timestamp.isoformat()
        return data
