"""Event and Alert dataclasses."""

from dataclasses import dataclass, asdict, field
from datetime import datetime
from typing import Optional, List


@dataclass
class SecurityEvent:
    """Represents a normalized security event from any OS."""
    
    id: Optional[int] = None
    created_at: Optional[datetime] = None
    event_time: Optional[datetime] = None
    host: Optional[str] = None
    process: Optional[str] = None
    pid: Optional[int] = None
    event_type: Optional[str] = None
    user: Optional[str] = None
    src_ip: Optional[str] = None
    dst_ip: Optional[str] = None
    severity: Optional[str] = None
    log_source: Optional[str] = None
    raw_message: Optional[str] = None
    os_name: Optional[str] = None
    
    # Legacy field aliases for backward compatibility
    @property
    def timestamp(self) -> Optional[datetime]:
        return self.event_time
    
    @timestamp.setter
    def timestamp(self, value: Optional[datetime]):
        self.event_time = value
    
    @property
    def username(self) -> Optional[str]:
        return self.user
    
    @username.setter
    def username(self, value: Optional[str]):
        self.user = value
    
    @property
    def source_ip(self) -> Optional[str]:
        return self.src_ip
    
    @source_ip.setter
    def source_ip(self, value: Optional[str]):
        self.src_ip = value
    
    @property
    def process_name(self) -> Optional[str]:
        return self.process
    
    @process_name.setter
    def process_name(self, value: Optional[str]):
        self.process = value
    
    def to_dict(self):
        """Convert to dictionary with ISO format timestamps."""
        return {
            'id': self.id,
            'created_at': self.created_at.isoformat() if self.created_at else None,
            'event_time': self.event_time.isoformat() if self.event_time else None,
            'timestamp': self.event_time.isoformat() if self.event_time else None,
            'host': self.host,
            'process': self.process,
            'process_name': self.process,
            'pid': self.pid,
            'event_type': self.event_type,
            'user': self.user,
            'username': self.user,
            'src_ip': self.src_ip,
            'source_ip': self.src_ip,
            'dst_ip': self.dst_ip,
            'severity': self.severity,
            'log_source': self.log_source,
            'raw_message': self.raw_message,
            'os_name': self.os_name,
        }


@dataclass
class Alert:
    """Represents a security alert generated by rules."""
    
    id: Optional[int] = None
    created_at: Optional[datetime] = None
    alert_type: Optional[str] = None
    description: Optional[str] = None
    severity: Optional[str] = None
    related_event_ids: Optional[str] = None
    status: Optional[str] = "active"
    
    # Legacy alias
    @property
    def timestamp(self) -> Optional[datetime]:
        return self.created_at
    
    @timestamp.setter
    def timestamp(self, value: Optional[datetime]):
        self.created_at = value
    
    def to_dict(self):
        """Convert to dictionary with ISO format timestamps."""
        return {
            'id': self.id,
            'created_at': self.created_at.isoformat() if self.created_at else None,
            'timestamp': self.created_at.isoformat() if self.created_at else None,
            'alert_type': self.alert_type,
            'description': self.description,
            'severity': self.severity,
            'related_event_ids': self.related_event_ids,
            'status': self.status,
        }
